Julie-kiwi/prelude

- Gemfile.lock
- app/controllers/event_controller.rb
- app/controllers/game_controller.rb
- app/controllers/library_controller.rb
- app/controllers/participant_controller.rb
- app/controllers/user_controller.rb
- app/views/event/create.html.erb
- app/views/event/destroy.html.erb
- app/views/event/new.html.erb
- app/views/event/show.html.erb
- app/views/game/create.html.erb
- app/views/game/new.html.erb
- app/views/game/show.html.erb
- app/views/library/create.html.erb
- app/views/library/delete.html.erb
- app/views/library/index.html.erb
- app/views/participant/create.html.erb
- app/views/participant/destroy.html.erb
- app/views/participant/index.html.erb
- app/views/participant/new.html.erb
- app/views/user/show.html.erb
- config/routes.rb
- test/controllers/event_controller_test.rb
- test/controllers/game_controller_test.rb
- test/controllers/library_controller_test.rb
- test/controllers/participant_controller_test.rb
- test/controllers/user_controller_test.rb
generate all controllers and routes
> generate all controllers + routes to be checked

- app/controllers/application_controller.rb
- app/controllers/user_controller.rb
- app/controllers/users_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
- app/views/user/show.html.erb
- app/views/users/show.html.erb
- config/routes.rb
Change routes from generator to resources
Rename controller and view for users that were badly generated
Add new validated fields in sign up form with permissions
Change link_to profile in navbar menu
> User controller show

- Gemfile
- Gemfile.lock
- app/models/event.rb
- app/views/events/new.html.erb
gem addition
small changes for invitations in event model and in event form
> Events enhancement

- app/assets/stylesheets/pages/_index.scss
> added css page for find game form

- db/seeds.rb
Seeds modification to destroy all created data when running rails db:seed
> seeds corrections to destroy everything when building seeds

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_game_search.scss
- app/javascript/packs/application.js
- app/javascript/packs/search_duration.js
- app/views/games/search.html.erb
better design on search page :)
> Search design

- app/helpers/application_helper.rb
- app/models/game.rb
- app/services/scrapping.rb
- app/views/games/search.html.erb
- db/seeds.rb
there was a pb in scrapping duration, it's now fixed :)
> Improved scrapping

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_link.scss
- app/assets/stylesheets/pages/_game_search.scss
- app/javascript/packs/players.js
- app/views/games/search.html.erb
improved the page search games :)
> Games#search

- app/assets/stylesheets/pages/_game_suggestions.scss
- app/assets/stylesheets/pages/_profile.scss
- app/javascript/packs/application.js
- app/views/users/show.html.erb
- package.json
- yarn.lock
> Profile page enhancement

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/pages/_game_search.scss
- app/assets/stylesheets/pages/_game_suggestions.scss
- app/helpers/application_helper.rb
- app/services/scrapping.rb
- app/views/games/suggestions.html.erb
- db/seeds.rb
- lib/games.yml
- lib/tasks/games_seeds.rake
fixed seed pb
front on Suggestions page is done !
> Games#suggestions

- Gemfile
- app/assets/stylesheets/pages/_games_show.scss
- app/views/games/show.html.erb
- db/seeds.rb
> Games#show

- app/views/shared/_participants-avatar.html.erb
> fix photo in event#show

- app/javascript/packs/application.js
add french language to js form in events_new_view
> js-flatpickr

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_event_show.scss
- app/assets/stylesheets/pages/_game_search.scss
- app/assets/stylesheets/pages/_game_suggestions.scss
- app/assets/stylesheets/pages/_profile.scss
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
Change list:
Navbar position to bottom
margins added to each pages for navbar
active classes for icons
> Navbar bottom

- app/assets/javascripts/manifest.json.erb
- app/assets/stylesheets/pages/_games_show.scss
- app/views/games/show.html.erb
> button-description games show

- app/views/devise/shared/_links.html.erb
- app/views/shared/_flashes.html.erb
- config/locales/devise.en.yml
Changes
Remove sweet alerts
Remove toto in login
> sweet alert removed

- app/models/event.rb
- app/views/events/show.html.erb
- app/views/pages/home_authenticate.html.erb
Changes:
- Add class method place_to for dashboard view
- Add class method address for event#show view
- Modification of views to display correct addresses
> correct addresses for creator or bar

- app/controllers/pages_controller.rb
- app/views/events/new.html.erb
- app/views/pages/home_authenticate.html.erb
Changes
- Email replaced by name in invitaion in new#event
- Change display in event in home page
> change email in event creation and home page event display corrected

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_event_show.scss
- app/assets/stylesheets/pages/_game_search.scss
- app/assets/stylesheets/pages/_game_suggestions.scss
- app/assets/stylesheets/pages/_home.scss
Changes:
- navbar resize to 60px
- all pages margin bot changed to 60px
> change navbar size and margin bot on all pages

- app/javascript/plugins/init_mapbox.js
> map new style

- app/assets/stylesheets/components/_button.scss
- app/models/event.rb
- app/views/events/show.html.erb
- app/views/pages/home_authenticate.html.erb
Changes:
- dates and times on french format
- button on event show change
> date and time format ok

- app/assets/stylesheets/pages/_game_search.scss
- app/assets/stylesheets/pages/_new.scss
Changes:
- remove margin 5px in event#new
- remove margin 5px in game#search
> views corrected

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home_unauthenticate.html.erb
Home rebuilt with no more absolute positions
> homepage done
